import java.io.File
import java.util.Base64

plugins {
    id("ygdrasil.conventions.kalligraphie-kmp-library")
}

/**
 * Kotlin/Native has no resource classpath: `getResourceAsStream` does not exist, so the iOS test
 * binary cannot read the Unicode conformance corpora the way the JVM and Android ones do. The
 * corpora the portable tests need are therefore embedded as generated Kotlin source, exactly as
 * `:kalligraphie:shaping` and `:kalligraphie:e2e` embed their fixtures: this task reads the declared
 * files and emits one chunked base64 string per resource.
 */
fun renderEmbeddedCorpus(
    entries: List<Pair<String, File>>,
    objectName: String,
    sourceTask: String,
): String {
    val sorted = entries.sortedBy { (resourcePath, _) -> resourcePath }
    val chunksByPath = sorted.associate { (resourcePath, file) ->
        resourcePath to Base64.getEncoder().encodeToString(file.readBytes()).chunked(32_768)
    }
    return buildString {
        appendLine("// @generated by :kalligraphie:unicode:$sourceTask — do not edit.")
        appendLine("package org.graphiks.kalligraphie.unicode.corpus")
        appendLine()
        appendLine("internal object $objectName {")
        appendLine("    internal val paths: Set<String> = setOf(")
        sorted.forEach { (resourcePath, _) -> appendLine("        \"$resourcePath\",") }
        appendLine("    )")
        appendLine()
        appendLine("    internal fun base64(relativePath: String): String = when (relativePath) {")
        chunksByPath.forEach { (resourcePath, chunks) ->
            appendLine("        \"$resourcePath\" -> listOf(")
            chunks.forEach { chunk -> appendLine("            \"$chunk\",") }
            appendLine("        ).joinToString(\"\")")
        }
        appendLine("        else -> error(\"The embedded Unicode corpus has no entry for \$relativePath.\")")
        appendLine("    }")
        appendLine("}")
    }
}

/**
 * The corpora the portable conformance tests read on a target without a class path.
 *
 * The two BiDi corpora are deliberately absent: they are 15 MB together, and the engine they
 * exercise is integer arithmetic over the module's own tables, whose behaviour on this target the
 * grapheme corpus and the table spot checks already establish. They run on the JVM and on Android.
 */
val iosCorpus by tasks.registering {
    group = "verification"
    description = "Embeds the Unicode conformance corpora into the iosSimulatorArm64Test binary."
    val resources = layout.projectDirectory.dir("src/harnessResources")
    val entries = listOf(
        "/unicode/16.0.0/GraphemeBreakTest.txt" to resources.file("unicode/16.0.0/GraphemeBreakTest.txt").asFile,
    )
    inputs.files(entries.map { (_, file) -> file }).withPropertyName("corpusFiles")
    val outputDirectory = layout.buildDirectory.dir("generated/ios-corpus/kotlin")
    outputs.dir(outputDirectory)
    doLast {
        val source = outputDirectory.get().asFile
            .resolve("org/graphiks/kalligraphie/unicode/corpus/EmbeddedUnicodeCorpusData.kt")
        source.parentFile.mkdirs()
        source.writeText(renderEmbeddedCorpus(entries, "EmbeddedUnicodeCorpusData", "iosCorpus"))
    }
}

/**
 * The corpora the portable web tests read, embedded for the same reason as the iOS ones.
 *
 * Only the grapheme corpus is needed: the web suite runs the portable conformance test, which reads
 * it and nothing else. The two BiDi corpora stay class-path-only for the size reason `iosCorpus`
 * documents, and the line-break corpus is likewise left to the JVM/Android class path.
 */
val webCorpus by tasks.registering {
    group = "verification"
    description = "Embeds the Unicode conformance corpora into the web (js/wasmJs) test binaries."
    val resources = layout.projectDirectory.dir("src/harnessResources")
    val entries = listOf(
        "/unicode/16.0.0/GraphemeBreakTest.txt" to resources.file("unicode/16.0.0/GraphemeBreakTest.txt").asFile,
    )
    inputs.files(entries.map { (_, file) -> file }).withPropertyName("corpusFiles")
    val outputDirectory = layout.buildDirectory.dir("generated/web-corpus/kotlin")
    outputs.dir(outputDirectory)
    doLast {
        val source = outputDirectory.get().asFile
            .resolve("org/graphiks/kalligraphie/unicode/corpus/EmbeddedWebCorpusData.kt")
        source.parentFile.mkdirs()
        source.writeText(renderEmbeddedCorpus(entries, "EmbeddedWebCorpusData", "webCorpus"))
    }
}

/** The directories of the shared conformance harness. */
val sharedHarnessDirs = listOf("src/sharedTest/kotlin")

/** The class-path corpus implementation, which only the JVM family can use. */
val classpathCorpusDir = "src/classpathTest/kotlin"

/** The Android test environment, shared by the host and device compilations so the two cannot drift. */
val androidFamilyDir = "src/androidFamilyTest/kotlin"

kotlin {
    android {
        withHostTest {}
        withDeviceTest {
            instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
            managedDevices {
                localDevices {
                    create("mediumPhone") {
                        device = "Medium Phone"
                        apiLevel = 35
                        systemImageSource = "aosp"
                    }
                }
            }
        }
    }

    sourceSets {
        commonMain.dependencies {
            api(project(":kalligraphie:api"))
        }
        jvmMain.dependencies {
            implementation(libs.icu4j)
        }
        commonTest.dependencies {
            implementation(project(":kalligraphie:api"))
            implementation(kotlin("test"))
        }
        jvmTest {
            // The Unicode conformance corpora and the tables generated from them: one committed
            // directory, wired as a resource directory wherever the platform has a class path.
            resources.srcDir(layout.projectDirectory.dir("src/harnessResources"))
            // The portable half of the conformance harness is shared, not duplicated: one copy of
            // its corpus seam and its corpus tests compiles into every test target that can run it.
            sharedHarnessDirs.forEach { directory -> kotlin.srcDir(directory) }
            kotlin.srcDir(classpathCorpusDir)
        }
        webTest.dependencies {
            implementation(kotlin("test"))
        }
        webTest {
            // Kotlin/JS and Kotlin/Wasm have no resource class path, so the grapheme corpus the
            // portable conformance test reads is embedded as generated source, exactly as on iOS.
            kotlin.srcDir(webCorpus)
            // The portable half of the conformance harness is shared, not duplicated.
            sharedHarnessDirs.forEach { directory -> kotlin.srcDir(directory) }
        }
        val androidHostTest by getting {
            dependencies {
                implementation(kotlin("test"))
            }
            // AGP puts these Kotlin resource directories on the unit-test class path, so the same
            // `/unicode/16.0.0/…` entries resolve here as they do on the JVM.
            resources.srcDir(layout.projectDirectory.dir("src/harnessResources"))
            sharedHarnessDirs.forEach { directory -> kotlin.srcDir(directory) }
            kotlin.srcDir(classpathCorpusDir)
            kotlin.srcDir(androidFamilyDir)
        }
        val androidDeviceTest by getting {
            dependencies {
                implementation(libs.androidx.test.ext.junit)
                implementation(libs.androidx.test.runner)
                implementation(kotlin("test"))
            }
            // AGP packages the same directory into the device-test APK, so the instrumented suite
            // reads the same committed corpus through the class loader.
            resources.srcDir(layout.projectDirectory.dir("src/harnessResources"))
            sharedHarnessDirs.forEach { directory -> kotlin.srcDir(directory) }
            kotlin.srcDir(classpathCorpusDir)
            kotlin.srcDir(androidFamilyDir)
        }
        val iosSimulatorArm64Test by getting {
            dependencies {
                implementation(kotlin("test"))
            }
            sharedHarnessDirs.forEach { directory -> kotlin.srcDir(directory) }
            kotlin.srcDir(iosCorpus)
        }
    }
}
