#!/usr/bin/env python3
"""Generates the committed sRGB<->linear-light transfer table for :kalligraphie:raster-cpu.

The table is data, not computation: committing it keeps the rasterizer free of pow()/exp() so
identical inputs produce identical bytes on the JVM, Android ART and Kotlin/Native.
"""

from __future__ import annotations

import pathlib

OUT = pathlib.Path(__file__).resolve().parents[2] / (
    "kalligraphie/raster-cpu/src/commonMain/kotlin/org/graphiks/kalligraphie/raster/SrgbTransfer.kt"
)


def to_linear(channel: int) -> int:
    value = channel / 255.0
    linear = value / 12.92 if value <= 0.04045 else ((value + 0.055) / 1.055) ** 2.4
    return int(round(linear * 65535))


def main() -> None:
    table = [to_linear(c) for c in range(256)]
    numbers = [str(value) for value in table]
    header = (
        "// Generated by scripts/raster/generate_srgb_transfer.py; do not edit by hand.\n"
        "package org.graphiks.kalligraphie.raster\n\n"
        "/** Committed sRGB<->linear-light transfer; see the generator for the exact formula. */\n"
        "internal object SrgbTransfer {\n"
        "    /** 16-bit linear-light value of each of the 256 sRGB channel literals. */\n"
        "    private val LINEAR: IntArray = intArrayOf(\n        "
    )
    body = ",\n        ".join(numbers)
    footer = (
        ",\n    )\n\n"
        "    /** Returns the 16-bit linear-light value of one 8-bit sRGB channel. */\n"
        "    fun toLinear(channel8: Int): Int = LINEAR[channel8]\n\n"
        "    /**\n"
        "     * Returns the nearest 8-bit sRGB channel for [linear16], choosing the highest sRGB\n"
        "     * channel whose linear value does not exceed it (a fixed, monotone tie rule).\n"
        "     */\n"
        "    fun toSrgb(linear16: Int): Int {\n"
        "        var low = 0\n"
        "        var high = 255\n"
        "        while (low < high) {\n"
        "            val middle = (low + high + 1) ushr 1\n"
        "            if (LINEAR[middle] <= linear16) low = middle else high = middle - 1\n"
        "        }\n"
        "        return low\n"
        "    }\n"
        "}\n"
    )
    OUT.write_text(header + body + footer, encoding="utf-8")


if __name__ == "__main__":
    main()
