package org.graphiks.kalligraphie

import org.graphiks.kalligraphie.api.DesignBounds
import org.graphiks.kalligraphie.api.FontAccessRequirementsSnapshot
import org.graphiks.kalligraphie.api.FontGlyphRequest
import org.graphiks.kalligraphie.api.FontInstanceDescriptor
import org.graphiks.kalligraphie.api.FontOperationResult
import org.graphiks.kalligraphie.api.FontRenderVariantKey
import org.graphiks.kalligraphie.api.FontSourceProvenance
import org.graphiks.kalligraphie.api.GlyphContour
import org.graphiks.kalligraphie.api.GlyphOutlineCommand
import org.graphiks.kalligraphie.api.GlyphRepresentation
import org.graphiks.kalligraphie.api.LayoutUnit
import org.graphiks.kalligraphie.api.OutlineProfile
import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertTrue

/**
 * End-to-end journeys over audited OpenType/CFF fixtures.
 *
 * Each fixture and its outline oracle are generated by fontTools (see the fixture
 * `PROVENANCE.md`), so these tests detect a regression in the portable CFF
 * decoder rather than restating its own output.
 */
class CffOpenTypeJourneyTest {
    @Test
    fun materializesTheAuditedCffGlyphFromThePortableOutlineRoute() {
        runJourney(
            otf = "/fonts/cff-liberation/LiberationSans-CFF.otf",
            oracle = "/fonts/cff-liberation/A-outline.txt",
            bounds = DesignBounds(4, 0, 1362, 1409),
        )
    }

    @Test
    fun materializesTheAuditedCff2GlyphFromThePortableOutlineRoute() {
        runJourney(
            otf = "/fonts/cff2-liberation/LiberationSans-CFF2.otf",
            oracle = "/fonts/cff2-liberation/A-outline.txt",
            bounds = DesignBounds(4, 0, 1362, 1409),
        )
    }

    @Test
    fun materializesTheAuditedVariableCff2DefaultInstance() {
        runJourney(
            otf = "/fonts/cff2-variable/SyntheticVariable-CFF2.otf",
            oracle = "/fonts/cff2-variable/A-outline.txt",
            bounds = DesignBounds(0, 0, 100, 200),
        )
    }

    private fun runJourney(otf: String, oracle: String, bounds: DesignBounds) {
        val bytes = fixture(otf)
        val catalog = success(Kalligraphie.embedded(bytes, FontSourceProvenance("fixture")))
        val face = catalog.faces.single()
        assertTrue(face.capabilities.outline, "The CFF face must advertise the outline route.")

        val resolver = success(catalog.openAssetResolver())
        val instance = success(
            success(catalog.resolveFace(face.id, outlineRequirements())).instantiate(FontInstanceDescriptor(LayoutUnit(2048f))),
        )
        val glyph = success(instance.resolveGlyph(0x41)).glyphId
        val asset = success(instance.acquireRenderAsset(resolver, FontRenderVariantKey.default, outlineRequirements()))
        try {
            val outline = assertIs<GlyphRepresentation.Outline>(
                success(asset.resolveGlyph(FontGlyphRequest(glyph))),
            ).outline
            assertContours(outline.contours, parseOracle(fixture(oracle).decodeToString()))
            assertEquals(bounds, outline.bounds)
        } finally {
            asset.close()
            resolver.close()
        }
    }

    private fun outlineRequirements(): FontAccessRequirementsSnapshot = FontAccessRequirementsSnapshot.renderable(
        OutlineProfile(
            maxBytes = 1_000_000,
            maxContours = 1_000,
            maxPoints = 100_000,
            maxCompositeDepth = 32,
            maxCompositeComponents = 1_024,
        ),
    )

    private fun parseOracle(text: String): List<List<String>> {
        val contours = ArrayList<List<String>>()
        var current = ArrayList<String>()
        for (line in text.trim().lines()) {
            val trimmed = line.trim()
            if (trimmed.isEmpty()) continue
            if (trimmed == "Z") {
                current.add(trimmed)
                contours.add(current)
                current = ArrayList()
            } else {
                current.add(trimmed)
            }
        }
        return contours
    }

    private fun assertContours(contours: List<GlyphContour>, oracle: List<List<String>>) {
        assertEquals(oracle.size, contours.size, "contour count")
        contours.forEachIndexed { contourIndex, contour ->
            val commands = contour.commands
            assertEquals(oracle[contourIndex].size, commands.size, "contour $contourIndex command count")
            commands.forEachIndexed { commandIndex, command ->
                val expected = oracle[contourIndex][commandIndex].split(" ")
                when (command) {
                    is GlyphOutlineCommand.MoveTo -> assertPoint("M", expected, command.x, command.y)
                    is GlyphOutlineCommand.LineTo -> assertPoint("L", expected, command.x, command.y)
                    is GlyphOutlineCommand.CubicTo -> {
                        assertEquals("C", expected[0], "contour $contourIndex command $commandIndex kind")
                        assertClose(expected[1].toDouble(), command.control1X)
                        assertClose(expected[2].toDouble(), command.control1Y)
                        assertClose(expected[3].toDouble(), command.control2X)
                        assertClose(expected[4].toDouble(), command.control2Y)
                        assertClose(expected[5].toDouble(), command.endX)
                        assertClose(expected[6].toDouble(), command.endY)
                    }

                    GlyphOutlineCommand.Close -> assertEquals("Z", expected[0])

                    is GlyphOutlineCommand.QuadraticTo -> error("CFF outlines must not contain quadratic segments.")
                }
            }
        }
    }

    private fun assertPoint(kind: String, expected: List<String>, x: Double, y: Double) {
        assertEquals(kind, expected[0])
        assertClose(expected[1].toDouble(), x)
        assertClose(expected[2].toDouble(), y)
    }

    private fun assertClose(expected: Double, actual: Double) {
        assertTrue(abs(expected - actual) < 1e-6, "expected $expected but was $actual")
    }

    private fun fixture(path: String): ByteArray =
        checkNotNull(javaClass.getResourceAsStream(path)) { "Missing fixture $path" }.use { it.readBytes() }

    private fun <T> success(result: FontOperationResult<T>): T = when (result) {
        is FontOperationResult.Success -> result.value
        is FontOperationResult.Failure -> error("expected success but was ${result.error}")
        is FontOperationResult.Cancelled -> error("expected success but was cancelled")
    }
}
