import java.io.File
import java.util.Base64

plugins {
    id("ygdrasil.conventions.kalligraphie-kmp-library")
}

tasks.withType<Test>().configureEach {
    jvmArgs("--enable-native-access=ALL-UNNAMED")
}

/**
 * B3: Kotlin/Native test binaries have no Gradle resource classpath (`getResourceAsStream` does not
 * exist on Kotlin/Native), and the `simctl`-spawned test process does not inherit the Gradle
 * `environment(...)` variables — `simctl spawn` only forwards variables carrying a `SIMCTL_CHILD_`
 * prefix, which the Kotlin Gradle plugin does not add. The shared fixture corpus is therefore
 * embedded into the iOS simulator test binary at build time: this task reads the real
 * `test-fixtures/` files (declared inputs) and emits a Kotlin source holding their base64 bytes,
 * mirroring the kffi iOS fixture packaging.
 */
fun renderIosFixtureCorpus(entries: List<Pair<String, File>>): String {
    val sorted = entries.sortedBy { (resourcePath, _) -> resourcePath }
    val chunksByPath = sorted.associate { (resourcePath, file) ->
        resourcePath to Base64.getEncoder().encodeToString(file.readBytes()).chunked(32_768)
    }
    return buildString {
        appendLine("// @generated by :kalligraphie:shaping:iosFixtureCorpus — do not edit.")
        appendLine("package org.graphiks.kalligraphie.shaping")
        appendLine()
        appendLine("internal object IosFixtureCorpus {")
        appendLine("    internal val paths: Set<String> = setOf(")
        sorted.forEach { (resourcePath, _) -> appendLine("        \"$resourcePath\",") }
        appendLine("    )")
        appendLine()
        appendLine("    internal fun base64(relativePath: String): String = when (relativePath) {")
        chunksByPath.forEach { (resourcePath, chunks) ->
            appendLine("        \"$resourcePath\" -> listOf(")
            chunks.forEach { chunk -> appendLine("            \"$chunk\",") }
            appendLine("        ).joinToString(\"\")")
        }
        appendLine("        else -> error(\"The embedded iOS fixture corpus has no entry for \$relativePath.\")")
        appendLine("    }")
        appendLine("}")
    }
}

val iosFixtureCorpus by tasks.registering {
    group = "verification"
    description = "Embeds the shared fixture corpus into the iosSimulatorArm64Test binary."
    val fixturesRoot = rootProject.layout.projectDirectory.dir("test-fixtures")
    val entries = listOf(
        "/fonts/dejavu/DejaVuSans.ttf" to fixturesRoot.file("fonts/dejavu/DejaVuSans.ttf").asFile,
        "/fonts/liberation/LiberationSans-Regular.ttf" to fixturesRoot.file("fonts/liberation/LiberationSans-Regular.ttf").asFile,
        "/fonts/amiri/Amiri-Regular.ttf" to fixturesRoot.file("fonts/amiri/Amiri-Regular.ttf").asFile,
        "/fonts/gdef-kern/GdefKerningFixture.ttf" to fixturesRoot.file("fonts/gdef-kern/GdefKerningFixture.ttf").asFile,
    )
    inputs.files(entries.map { (_, file) -> file }).withPropertyName("fixtureFiles")
    val outputDirectory = layout.buildDirectory.dir("generated/ios-fixture-corpus/kotlin")
    outputs.dir(outputDirectory)
    doLast {
        val source = outputDirectory.get().asFile
            .resolve("org/graphiks/kalligraphie/shaping/IosFixtureCorpus.kt")
        source.parentFile.mkdirs()
        source.writeText(renderIosFixtureCorpus(entries))
    }
}

kotlin {
    android {
        withDeviceTest {
            instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
            managedDevices {
                localDevices {
                    create("mediumPhone") {
                        device = "Medium Phone"
                        apiLevel = 35
                        systemImageSource = "aosp"
                    }
                }
            }
        }
    }
    sourceSets {
        commonMain.dependencies {
            api(project(":kalligraphie:api"))
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
        }
        iosMain.dependencies {
            implementation(libs.kotlinx.atomicfu)
            implementation(libs.kffi.harfbuzz)
        }
        jvmMain.dependencies {
            implementation(libs.kffi.harfbuzz.jvm)
        }
        androidMain.dependencies {
            implementation(libs.kffi.harfbuzz.android)
        }
        jvmTest.dependencies {
            implementation(project(":kalligraphie"))
            implementation(project(":kalligraphie:unicode"))
            implementation(project(":kalligraphie:font:core"))
            implementation(project(":kalligraphie:font:sfnt"))
            implementation(kotlin("test"))
        }
        jvmTest {
            resources.srcDir(rootProject.file("test-fixtures"))
        }
        val androidDeviceTest by getting {
            dependencies {
                implementation(project(":kalligraphie"))
                implementation(project(":kalligraphie:unicode"))
                implementation(project(":kalligraphie:font:core"))
                implementation(project(":kalligraphie:font:sfnt"))
                implementation(libs.androidx.test.ext.junit)
                implementation(libs.androidx.test.runner)
                implementation(kotlin("test"))
            }
            // The shared JVM fixture corpus is reused on-device: AGP packages this Kotlin
            // resource directory into the device-test APK, so the suite resolves the same
            // `/fonts/...` entries through the class loader as `jvmTest`.
            resources.srcDir(rootProject.file("test-fixtures"))
            // B4: `androidDeviceTest` cannot see `commonTest` in this module (verified: hoisting
            // `ShapingGolden.kt` into `commonTest` fails `compileAndroidDeviceTest` with an
            // unresolved `canonicalShapingGolden`). A neutral directory added to both device-test
            // source sets keeps exactly one serializer without duplication.
            kotlin.srcDir("src/sharedTest/kotlin")
        }
        val iosSimulatorArm64Test by getting {
            // B3: the shared fixture corpus is embedded as generated Kotlin source because
            // Kotlin/Native has no resource classpath and the simctl-spawned test process cannot
            // receive the Gradle `environment(...)` path (see iosFixtureCorpus above).
            kotlin.srcDir(iosFixtureCorpus)
            // B4: the same neutral directory the Android device test compiles.
            kotlin.srcDir("src/sharedTest/kotlin")
            dependencies {
                implementation(project(":kalligraphie"))
                implementation(project(":kalligraphie:unicode"))
                implementation(project(":kalligraphie:font:core"))
                implementation(project(":kalligraphie:font:sfnt"))
                implementation(libs.kotlinx.coroutines.core)
                implementation(kotlin("test"))
            }
        }
    }
}

configurations.configureEach {
    resolutionStrategy.cacheChangingModulesFor(0, "seconds")
}
