import java.io.File
import java.util.Base64

plugins {
    id("ygdrasil.conventions.kmp-web-library")
    // The web test bundle links the same WebAssembly HarfBuzz the library ships, so the authored
    // glue and the Emscripten module must be extracted where the bundler resolves them.
    id("ygdrasil.conventions.kalligraphie-kffi-harfbuzz-web-runtime")
}

/**
 * Kotlin/Native and Kotlin/Wasm have no resource classpath: neither can read `test-fixtures/` the way
 * the JVM and Android ones do. The corpus they need is therefore embedded as generated Kotlin source,
 * exactly as `:kalligraphie:shaping` embeds its iOS fixtures: this task reads the declared files and
 * emits one chunked base64 string per resource.
 */
fun renderEmbeddedCorpus(entries: List<Pair<String, File>>, sourceTask: String): String {
    val sorted = entries.sortedBy { (resourcePath, _) -> resourcePath }
    val chunksByPath = sorted.associate { (resourcePath, file) ->
        resourcePath to Base64.getEncoder().encodeToString(file.readBytes()).chunked(32_768)
    }
    return buildString {
        appendLine("// @generated by :kalligraphie:e2e:$sourceTask — do not edit.")
        appendLine("package org.graphiks.kalligraphie.e2e.fixture")
        appendLine()
        appendLine("internal object E2eFixtureCorpus {")
        appendLine("    internal val paths: Set<String> = setOf(")
        sorted.forEach { (resourcePath, _) -> appendLine("        \"$resourcePath\",") }
        appendLine("    )")
        appendLine()
        appendLine("    internal fun base64(relativePath: String): String = when (relativePath) {")
        chunksByPath.forEach { (resourcePath, chunks) ->
            appendLine("        \"$resourcePath\" -> listOf(")
            chunks.forEach { chunk -> appendLine("            \"$chunk\",") }
            appendLine("        ).joinToString(\"\")")
        }
        appendLine("        else -> error(\"The embedded harness corpus has no entry for \$relativePath.\")")
        appendLine("    }")
        appendLine("}")
    }
}

/**
 * The corpus every target without a resource classpath reads: the families both registries of
 * renderers and the probes load, plus the committed resources the verifier and the ratchet read.
 * Every entry is named by a scene or a probe the suite runs on these targets.
 *
 * `test-fixtures/` is shared with the JVM and Android corpora; `src/harnessResources/` holds the
 * committed golden manifest and the auto-sizing exemptions.
 */
val e2eHarnessCorpusEntries: List<Pair<String, File>> = run {
    val fixtures = rootProject.layout.projectDirectory.dir("test-fixtures")
    val resources = layout.projectDirectory.dir("src/harnessResources")
    listOf(
        "/fonts/liberation/LiberationSans-Regular.ttf" to fixtures.file("fonts/liberation/LiberationSans-Regular.ttf").asFile,
        "/fonts/amiri/Amiri-Regular.ttf" to fixtures.file("fonts/amiri/Amiri-Regular.ttf").asFile,
        "/fonts/noto-devanagari/NotoSansDevanagari-Regular.ttf" to fixtures.file("fonts/noto-devanagari/NotoSansDevanagari-Regular.ttf").asFile,
        "/fonts/bungee-color/BungeeColor-Regular.ttf" to fixtures.file("fonts/bungee-color/BungeeColor-Regular.ttf").asFile,
        "/fonts/emoji-two-colr-v0/EmojiTwoCOLRv0.ttf" to fixtures.file("fonts/emoji-two-colr-v0/EmojiTwoCOLRv0.ttf").asFile,
        "/fonts/skia-ebdt-format1/ebdt_fmt1.ttf" to fixtures.file("fonts/skia-ebdt-format1/ebdt_fmt1.ttf").asFile,
        "/fonts/skia-cbdt/cbdt.ttf" to fixtures.file("fonts/skia-cbdt/cbdt.ttf").asFile,
        "/fonts/skia-sbix/sbix.ttf" to fixtures.file("fonts/skia-sbix/sbix.ttf").asFile,
        "/fonts/cff-liberation/LiberationSans-CFF.otf" to fixtures.file("fonts/cff-liberation/LiberationSans-CFF.otf").asFile,
        "/fonts/cff2-liberation/LiberationSans-CFF2.otf" to fixtures.file("fonts/cff2-liberation/LiberationSans-CFF2.otf").asFile,
        "/fonts/kalligraphie-var-vvar/KalligraphieVarVVAR.ttf" to fixtures.file("fonts/kalligraphie-var-vvar/KalligraphieVarVVAR.ttf").asFile,
        "/fonts/kalligraphie-var-colr/KalligraphieVarCOLRv1.ttf" to fixtures.file("fonts/kalligraphie-var-colr/KalligraphieVarCOLRv1.ttf").asFile,
        "/fonts/kalniaglaze/KalniaGlaze[wdth,wght].ttf" to fixtures.file("fonts/kalniaglaze/KalniaGlaze[wdth,wght].ttf").asFile,
        // The paragraph scenes' own fixtures: the variable family the weight ladder walks and the
        // vertical Japanese face the mosaic composes.
        "/fonts/worksans/WorkSans[wght].ttf" to fixtures.file("fonts/worksans/WorkSans[wght].ttf").asFile,
        "/fonts/noto-sans-jp/NotoSansJP-VerticalFixture.ttf" to fixtures.file("fonts/noto-sans-jp/NotoSansJP-VerticalFixture.ttf").asFile,
        // The container scenes and their robustness probes: the same IBMPlexSans face wrapped in
        // both a WOFF 1.0 and a WOFF 2.0 container.
        "/fonts/woff-ibm-plex/IBMPlexSans-Regular.woff" to fixtures.file("fonts/woff-ibm-plex/IBMPlexSans-Regular.woff").asFile,
        "/fonts/woff-ibm-plex/IBMPlexSans-Regular.woff2" to fixtures.file("fonts/woff-ibm-plex/IBMPlexSans-Regular.woff2").asFile,
        // The journeys' own fixtures, which no scene reads: the Latin, Arabic and vertical CJK faces
        // the typography journeys lay out, the kerning face the incremental session is built on, and
        // the CFF faces with the fontTools outline oracles they are checked against.
        "/fonts/dejavu/DejaVuSans.ttf" to fixtures.file("fonts/dejavu/DejaVuSans.ttf").asFile,
        "/fonts/gdef-kern/GdefKerningFixture.ttf" to fixtures.file("fonts/gdef-kern/GdefKerningFixture.ttf").asFile,
        "/fonts/cff-liberation/A-outline.txt" to fixtures.file("fonts/cff-liberation/A-outline.txt").asFile,
        "/fonts/cff2-liberation/A-outline.txt" to fixtures.file("fonts/cff2-liberation/A-outline.txt").asFile,
        "/fonts/cff2-variable/SyntheticVariable-CFF2.otf" to fixtures.file("fonts/cff2-variable/SyntheticVariable-CFF2.otf").asFile,
        "/fonts/cff2-variable/A-outline.txt" to fixtures.file("fonts/cff2-variable/A-outline.txt").asFile,
        "/catalog/auto-sizing-exemptions.tsv" to resources.file("catalog/auto-sizing-exemptions.tsv").asFile,
        "/golden/manifest.tsv" to resources.file("golden/manifest.tsv").asFile,
    )
}

/**
 * The corpus the iOS simulator harness reads: embedded because Kotlin/Native has no resource class
 * path and the `simctl`-spawned test process does not inherit the Gradle environment.
 */
val iosFixtureCorpus by tasks.registering {
    group = "verification"
    description = "Embeds the iOS harness corpus into the iosSimulatorArm64Test binary."
    val entries = e2eHarnessCorpusEntries
    inputs.files(entries.map { (_, file) -> file }).withPropertyName("fixtureFiles")
    val outputDirectory = layout.buildDirectory.dir("generated/ios-fixture-corpus/kotlin")
    outputs.dir(outputDirectory)
    doLast {
        val source = outputDirectory.get().asFile
            .resolve("org/graphiks/kalligraphie/e2e/fixture/E2eFixtureCorpus.kt")
        source.parentFile.mkdirs()
        source.writeText(renderEmbeddedCorpus(entries, "iosFixtureCorpus"))
    }
}

/**
 * The corpus the web (js/wasmJs) harness reads: embedded for the same reason as the iOS one, since
 * neither Kotlin/JS nor Kotlin/Wasm gives a test binary a resource class path.
 */
val webFixtureCorpus by tasks.registering {
    group = "verification"
    description = "Embeds the web harness corpus into the js and wasmJs test bundles."
    val entries = e2eHarnessCorpusEntries
    inputs.files(entries.map { (_, file) -> file }).withPropertyName("fixtureFiles")
    val outputDirectory = layout.buildDirectory.dir("generated/web-fixture-corpus/kotlin")
    outputs.dir(outputDirectory)
    doLast {
        val source = outputDirectory.get().asFile
            .resolve("org/graphiks/kalligraphie/e2e/fixture/E2eFixtureCorpus.kt")
        source.parentFile.mkdirs()
        source.writeText(renderEmbeddedCorpus(entries, "webFixtureCorpus"))
    }
}

/** The directories of the shared harness: its scenes, verifier and ratchets. */
val sharedHarnessDirs = listOf("src/sharedTest/kotlin")

/** The class-path corpus implementation, which only the JVM family can use. */
val classpathCorpusDir = "src/classpathTest/kotlin"

/**
 * The journeys: the end-to-end scenarios that assert behaviour through the facades rather than
 * through a committed fingerprint. Their sources are portable — they read every byte through the
 * injected `FixtureCorpus` — so what keeps them off one compilation is its runtime, not its
 * language: every journey composes text, and the Android host unit test runs on a JVM that cannot
 * load the shared library the shaping route needs. The three targets that serve them are the JVM,
 * the Android device runtime and the iOS simulator, the same three that verify the composed scenes.
 */
val journeyDirs = listOf("src/journeyTest/kotlin")

kotlin {
    explicitApi()

    android {
        withHostTest {}
        withDeviceTest {
            instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
            managedDevices {
                localDevices {
                    create("mediumPhone") {
                        device = "Medium Phone"
                        apiLevel = 35
                        systemImageSource = "aosp"
                    }
                }
            }
        }
    }

    // The shared suite renders the whole catalog inside `runTest`, which is far slower than Mocha's
    // two-second default: the timeout is raised to cover the work each Node run actually does.
    js {
        nodejs {
            testTask {
                useMocha { timeout = "10m" }
            }
        }
    }
    wasmJs {
        nodejs {
            testTask {
                useMocha { timeout = "10m" }
            }
        }
    }

    sourceSets {
        commonMain.dependencies {
            api(project(":kalligraphie:api"))
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
        jvmTest.dependencies {
            implementation(project(":kalligraphie"))
            implementation(project(":kalligraphie:conformance"))
            implementation(project(":kalligraphie:raster-cpu"))
            implementation(project(":kalligraphie:layout"))
            implementation(project(":kalligraphie:shaping"))
            implementation(project(":kalligraphie:unicode"))
            implementation(project(":kalligraphie:font:core"))
            implementation(project(":kalligraphie:font:sfnt"))
            implementation(kotlin("test"))
            // The shared harness awaits `initialize()` through `runTest`; on JVM/Android/iOS it is a
            // no-op, but the same shared source must compile against it everywhere.
            implementation(libs.kotlinx.coroutines.test)
        }
        webTest.dependencies {
            implementation(project(":kalligraphie"))
            implementation(project(":kalligraphie:conformance"))
            implementation(project(":kalligraphie:raster-cpu"))
            implementation(project(":kalligraphie:layout"))
            implementation(project(":kalligraphie:shaping"))
            implementation(project(":kalligraphie:unicode"))
            implementation(project(":kalligraphie:font:core"))
            implementation(project(":kalligraphie:font:sfnt"))
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
        }
        webTest {
            // Neither Kotlin/JS nor Kotlin/Wasm has a resource class path, so the fonts and the
            // committed golden manifest are embedded as generated source, exactly as on iOS.
            kotlin.srcDir(webFixtureCorpus)
            sharedHarnessDirs.forEach { directory -> kotlin.srcDir(directory) }
        }
        jvmTest {
            resources.srcDir(rootProject.file("test-fixtures"))
            resources.srcDir(layout.projectDirectory.dir("src/harnessResources"))
            // The harness is shared, not duplicated: one copy of the scenes, of the
            // verification and of the ratchets compiles into every test target that can run it.
            sharedHarnessDirs.forEach { directory -> kotlin.srcDir(directory) }
            kotlin.srcDir(classpathCorpusDir)
            journeyDirs.forEach { directory -> kotlin.srcDir(directory) }
        }
        val androidHostTest by getting {
            dependencies {
                implementation(project(":kalligraphie"))
                implementation(project(":kalligraphie:conformance"))
                implementation(project(":kalligraphie:raster-cpu"))
                implementation(kotlin("test"))
                implementation(libs.kotlinx.coroutines.test)
            }
            // AGP puts these Kotlin resource directories on the unit-test class path, so the same
            // `/fonts/…` and `/golden/…` entries resolve here as they do on the JVM.
            resources.srcDir(rootProject.file("test-fixtures"))
            resources.srcDir(layout.projectDirectory.dir("src/harnessResources"))
            sharedHarnessDirs.forEach { directory -> kotlin.srcDir(directory) }
            kotlin.srcDir(classpathCorpusDir)
            // The host and the device compilations share the harness but not the environment: the
            // host runs on a JVM and cannot load the Android native artifact, so it declares only
            // the capabilities its runtime serves. Each directory holds exactly one declaration.
            kotlin.srcDir("src/androidHostTest/kotlin")
            // The journeys are absent here for that same reason and not because of where they are
            // written: they compose text, so this compilation could not run them.
        }
        val androidDeviceTest by getting {
            dependencies {
                implementation(project(":kalligraphie"))
                implementation(project(":kalligraphie:conformance"))
                implementation(project(":kalligraphie:raster-cpu"))
                implementation(libs.androidx.test.ext.junit)
                implementation(libs.androidx.test.runner)
                implementation(kotlin("test"))
                implementation(libs.kotlinx.coroutines.test)
            }
            // AGP packages the same directories into the device-test APK, so the instrumented suite
            // reads the same committed corpus through the class loader.
            resources.srcDir(rootProject.file("test-fixtures"))
            resources.srcDir(layout.projectDirectory.dir("src/harnessResources"))
            sharedHarnessDirs.forEach { directory -> kotlin.srcDir(directory) }
            kotlin.srcDir(classpathCorpusDir)
            kotlin.srcDir("src/androidDeviceTest/kotlin")
            journeyDirs.forEach { directory -> kotlin.srcDir(directory) }
        }
        val iosSimulatorArm64Test by getting {
            dependencies {
                implementation(project(":kalligraphie"))
                implementation(project(":kalligraphie:conformance"))
                implementation(project(":kalligraphie:raster-cpu"))
                implementation(kotlin("test"))
                implementation(libs.kotlinx.coroutines.test)
            }
            sharedHarnessDirs.forEach { directory -> kotlin.srcDir(directory) }
            journeyDirs.forEach { directory -> kotlin.srcDir(directory) }
            kotlin.srcDir(iosFixtureCorpus)
        }
    }
}

tasks.withType<Test>().configureEach {
    jvmArgs("--enable-native-access=ALL-UNNAMED")
}

/**
 * The generators run on the test runtime class path: they read the same scene catalog and the same
 * fixture corpus the verification does, they just write the committed artefacts instead of
 * asserting them. Nothing about the project's correctness is claimed here, which is why they are
 * tasks and not tests: the suite no longer excludes a single class from `check`.
 */
val writerOnce = tasks.withType<JavaExec>().configureEach {
    jvmArgs("--enable-native-access=ALL-UNNAMED")
    classpath = tasks.named<Test>("jvmTest").get().classpath
    mainClass.set("org.graphiks.kalligraphie.e2e.golden.GoldenWriterMainKt")
}

tasks.register<JavaExec>("updateE2eGolden") {
    group = "verification"
    description = "Regenerates the committed golden fingerprint manifest, the catalog matrix and the table claims from the scene catalog."
    args("manifest", "matrix", "claims")
}

tasks.register<JavaExec>("e2eGoldenDumps") {
    group = "verification"
    description = "Writes the golden inspection dumps outside the repository; requires -Pkalligraphie.e2e.dumps=<absolute directory>."
    val output = providers.gradleProperty("kalligraphie.e2e.dumps")
    doFirst {
        val directory = output.orNull
            ?: error("pass -Pkalligraphie.e2e.dumps=<absolute directory outside the repository>")
        args("dumps=$directory")
    }
}
