import java.io.File
import java.util.Base64

plugins {
    id("ygdrasil.conventions.kmp-library")
}

/**
 * Kotlin/Native has no resource classpath: `getResourceAsStream` does not exist, so the iOS test
 * binary cannot read `test-fixtures/` the way the JVM and Android ones do. The corpus it needs is
 * therefore embedded as generated Kotlin source, exactly as `:kalligraphie:shaping` embeds its iOS
 * fixtures: this task reads the declared files and emits one chunked base64 string per resource.
 */
fun renderEmbeddedCorpus(entries: List<Pair<String, File>>): String {
    val sorted = entries.sortedBy { (resourcePath, _) -> resourcePath }
    val chunksByPath = sorted.associate { (resourcePath, file) ->
        resourcePath to Base64.getEncoder().encodeToString(file.readBytes()).chunked(32_768)
    }
    return buildString {
        appendLine("// @generated by :kalligraphie:e2e:iosFixtureCorpus — do not edit.")
        appendLine("package org.graphiks.kalligraphie.e2e.fixture")
        appendLine()
        appendLine("internal object E2eFixtureCorpus {")
        appendLine("    internal val paths: Set<String> = setOf(")
        sorted.forEach { (resourcePath, _) -> appendLine("        \"$resourcePath\",") }
        appendLine("    )")
        appendLine()
        appendLine("    internal fun base64(relativePath: String): String = when (relativePath) {")
        chunksByPath.forEach { (resourcePath, chunks) ->
            appendLine("        \"$resourcePath\" -> listOf(")
            chunks.forEach { chunk -> appendLine("            \"$chunk\",") }
            appendLine("        ).joinToString(\"\")")
        }
        appendLine("        else -> error(\"The embedded harness corpus has no entry for \$relativePath.\")")
        appendLine("    }")
        appendLine("}")
    }
}

/**
 * The corpus the portable harness reads, and nowhere else: the families the portable scenes and the
 * probes load, plus the committed resources the verifier and the ratchet read. The paragraph-facade
 * scenes are absent on purpose — they do not run on this target, so their fonts would only bloat the
 * binary.
 */
val iosFixtureCorpus by tasks.registering {
    group = "verification"
    description = "Embeds the portable harness corpus into the iosSimulatorArm64Test binary."
    val fixtures = rootProject.layout.projectDirectory.dir("test-fixtures")
    val resources = layout.projectDirectory.dir("src/harnessResources")
    val entries = listOf(
        "/fonts/liberation/LiberationSans-Regular.ttf" to fixtures.file("fonts/liberation/LiberationSans-Regular.ttf").asFile,
        "/fonts/amiri/Amiri-Regular.ttf" to fixtures.file("fonts/amiri/Amiri-Regular.ttf").asFile,
        "/fonts/noto-devanagari/NotoSansDevanagari-Regular.ttf" to fixtures.file("fonts/noto-devanagari/NotoSansDevanagari-Regular.ttf").asFile,
        "/fonts/bungee-color/BungeeColor-Regular.ttf" to fixtures.file("fonts/bungee-color/BungeeColor-Regular.ttf").asFile,
        "/fonts/emoji-two-colr-v0/EmojiTwoCOLRv0.ttf" to fixtures.file("fonts/emoji-two-colr-v0/EmojiTwoCOLRv0.ttf").asFile,
        "/fonts/skia-ebdt-format1/ebdt_fmt1.ttf" to fixtures.file("fonts/skia-ebdt-format1/ebdt_fmt1.ttf").asFile,
        "/fonts/skia-cbdt/cbdt.ttf" to fixtures.file("fonts/skia-cbdt/cbdt.ttf").asFile,
        "/fonts/skia-sbix/sbix.ttf" to fixtures.file("fonts/skia-sbix/sbix.ttf").asFile,
        "/fonts/cff-liberation/LiberationSans-CFF.otf" to fixtures.file("fonts/cff-liberation/LiberationSans-CFF.otf").asFile,
        "/fonts/cff2-liberation/LiberationSans-CFF2.otf" to fixtures.file("fonts/cff2-liberation/LiberationSans-CFF2.otf").asFile,
        "/fonts/kalligraphie-var-vvar/KalligraphieVarVVAR.ttf" to fixtures.file("fonts/kalligraphie-var-vvar/KalligraphieVarVVAR.ttf").asFile,
        "/fonts/kalligraphie-var-colr/KalligraphieVarCOLRv1.ttf" to fixtures.file("fonts/kalligraphie-var-colr/KalligraphieVarCOLRv1.ttf").asFile,
        "/catalog/auto-sizing-exemptions.tsv" to resources.file("catalog/auto-sizing-exemptions.tsv").asFile,
        "/golden/manifest.tsv" to resources.file("golden/manifest.tsv").asFile,
    )
    inputs.files(entries.map { (_, file) -> file }).withPropertyName("fixtureFiles")
    val outputDirectory = layout.buildDirectory.dir("generated/ios-fixture-corpus/kotlin")
    outputs.dir(outputDirectory)
    doLast {
        val source = outputDirectory.get().asFile
            .resolve("org/graphiks/kalligraphie/e2e/fixture/E2eFixtureCorpus.kt")
        source.parentFile.mkdirs()
        source.writeText(renderEmbeddedCorpus(entries))
    }
}

/** The directories of the shared harness: its scenes, verifier and ratchets. */
val sharedHarnessDirs = listOf("src/sharedTest/kotlin")

/** The class-path corpus implementation, which only the JVM family can use. */
val classpathCorpusDir = "src/classpathTest/kotlin"

kotlin {
    explicitApi()

    android {
        withHostTest {}
        withDeviceTest {
            instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
            managedDevices {
                localDevices {
                    create("mediumPhone") {
                        device = "Medium Phone"
                        apiLevel = 35
                        systemImageSource = "aosp"
                    }
                }
            }
        }
    }

    sourceSets {
        commonMain.dependencies {
            api(project(":kalligraphie:api"))
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
        jvmTest.dependencies {
            implementation(project(":kalligraphie"))
            implementation(project(":kalligraphie:conformance"))
            implementation(project(":kalligraphie:raster-cpu"))
            implementation(project(":kalligraphie:layout"))
            implementation(project(":kalligraphie:shaping"))
            implementation(project(":kalligraphie:unicode"))
            implementation(project(":kalligraphie:font:core"))
            implementation(project(":kalligraphie:font:sfnt"))
            implementation(kotlin("test"))
        }
        jvmTest {
            resources.srcDir(rootProject.file("test-fixtures"))
            resources.srcDir(layout.projectDirectory.dir("src/harnessResources"))
            // The harness is shared, not duplicated: one copy of the portable scenes, of the
            // verification and of the ratchets compiles into every test target that can run it.
            sharedHarnessDirs.forEach { directory -> kotlin.srcDir(directory) }
            kotlin.srcDir(classpathCorpusDir)
        }
        val androidHostTest by getting {
            dependencies {
                implementation(project(":kalligraphie"))
                implementation(project(":kalligraphie:conformance"))
                implementation(project(":kalligraphie:raster-cpu"))
                implementation(kotlin("test"))
            }
            // AGP puts these Kotlin resource directories on the unit-test class path, so the same
            // `/fonts/…` and `/golden/…` entries resolve here as they do on the JVM.
            resources.srcDir(rootProject.file("test-fixtures"))
            resources.srcDir(layout.projectDirectory.dir("src/harnessResources"))
            sharedHarnessDirs.forEach { directory -> kotlin.srcDir(directory) }
            kotlin.srcDir(classpathCorpusDir)
            kotlin.srcDir("src/androidFamilyTest/kotlin")
        }
        val androidDeviceTest by getting {
            dependencies {
                implementation(project(":kalligraphie"))
                implementation(project(":kalligraphie:conformance"))
                implementation(project(":kalligraphie:raster-cpu"))
                implementation(libs.androidx.test.ext.junit)
                implementation(libs.androidx.test.runner)
                implementation(kotlin("test"))
            }
            // AGP packages the same directories into the device-test APK, so the instrumented suite
            // reads the same committed corpus through the class loader.
            resources.srcDir(rootProject.file("test-fixtures"))
            resources.srcDir(layout.projectDirectory.dir("src/harnessResources"))
            sharedHarnessDirs.forEach { directory -> kotlin.srcDir(directory) }
            kotlin.srcDir(classpathCorpusDir)
            kotlin.srcDir("src/androidFamilyTest/kotlin")
        }
        val iosSimulatorArm64Test by getting {
            dependencies {
                implementation(project(":kalligraphie"))
                implementation(project(":kalligraphie:conformance"))
                implementation(project(":kalligraphie:raster-cpu"))
                implementation(kotlin("test"))
            }
            sharedHarnessDirs.forEach { directory -> kotlin.srcDir(directory) }
            kotlin.srcDir(iosFixtureCorpus)
        }
    }
}

tasks.withType<Test>().configureEach {
    jvmArgs("--enable-native-access=ALL-UNNAMED")
}

val updateClass = "org.graphiks.kalligraphie.e2e.golden.GoldenUpdateRunnerTest"
val dumpClass = "org.graphiks.kalligraphie.e2e.golden.GoldenDumpRunnerTest"
val matrixClass = "org.graphiks.kalligraphie.e2e.catalog.CatalogMatrixRunnerTest"
val claimsClass = "org.graphiks.kalligraphie.e2e.catalog.CatalogClaimsRunnerTest"
val e2eJvmTestTask = tasks.named<Test>("jvmTest")

e2eJvmTestTask.configure {
    filter.excludeTestsMatching(updateClass)
    filter.excludeTestsMatching(dumpClass)
    // Only the writers are excluded: the freshness tests must keep running under `check`.
    filter.excludeTestsMatching("$matrixClass.writesTheMatrixOnlyWhenExplicitlyEnabled")
    filter.excludeTestsMatching("$claimsClass.writesTheClaimsOnlyWhenExplicitlyEnabled")
}

tasks.register<Test>("updateE2eGolden") {
    group = "verification"
    description = "Regenerates the committed golden fingerprint manifest, the catalog matrix and the table claims from the scene catalog."
    testClassesDirs = e2eJvmTestTask.get().testClassesDirs
    classpath = e2eJvmTestTask.get().classpath
    filter.includeTestsMatching("$updateClass.writesTheManifestOnlyWhenExplicitlyEnabled")
    filter.includeTestsMatching("$matrixClass.writesTheMatrixOnlyWhenExplicitlyEnabled")
    filter.includeTestsMatching("$claimsClass.writesTheClaimsOnlyWhenExplicitlyEnabled")
    environment("KALLIGRAPHIE_E2E_UPDATE", "true")
    environment("KALLIGRAPHIE_E2E_MATRIX", "true")
    environment("KALLIGRAPHIE_E2E_CLAIMS", "true")
    outputs.upToDateWhen { false }
}

tasks.register<Test>("e2eGoldenDumps") {
    group = "verification"
    description = "Writes opt-in golden inspection dumps outside the repository."
    testClassesDirs = e2eJvmTestTask.get().testClassesDirs
    classpath = e2eJvmTestTask.get().classpath
    filter.includeTestsMatching("$dumpClass.writesDumpsOnlyWhenExplicitlyEnabled")
    environment("KALLIGRAPHIE_E2E_DUMPS", "true")
    outputs.upToDateWhen { false }
}
