#!/usr/bin/env python3
"""Generates the portable hyphenation pattern source from the vendored pattern file.

The American-English pattern set lives in the JVM module's resources as
`hyph-en-us.pat.txt`; the JVM provider reads that resource at runtime and verifies
its SHA-256 before building the service. Kotlin/Native has no class path and no
runtime digest machinery, so the portable provider takes the same pattern set from
a generated Kotlin source instead: this script reads the vendored file, verifies it
against the pinned digest below, and emits `EmbeddedHyphenationPatterns.kt` with
the pattern text as a single constant.

Run from the repository root:

    python3 scripts/unicode/generate_hyphenation_source.py --write
    python3 scripts/unicode/generate_hyphenation_source.py --check

`--check` re-emits the source in memory and compares it byte for byte with the
committed file, the same proof of non-drift the UCD table generator gives.
"""
import argparse
import hashlib
import pathlib

PATTERN_RESOURCE = "kalligraphie/unicode/src/jvmMain/resources/hyphenation/hyph-en-us.pat.txt"
TARGET = "kalligraphie/unicode/src/commonMain/kotlin/org/graphiks/kalligraphie/unicode/EmbeddedHyphenationPatterns.kt"
PINNED_SHA256 = "0f57318b878b132547ae92db39a6e1d1cf2a05d9008874955d6ecb910007a463"
MAX_LINE_WIDTH = 96
CHUNK = 12000


def chunk_text(value: str) -> list[str]:
    """Splits [value] into string-literal chunks of at most CHUNK characters, escaping Kotlin."""
    chunks = []
    position = 0
    while position < len(value):
        piece = value[position:position + CHUNK]
        escaped = piece.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "\\r")
        chunks.append(escaped)
        position += CHUNK
    return chunks


def render(pattern_text: str) -> str:
    digest = hashlib.sha256(pattern_text.encode("ascii")).hexdigest()
    if digest != PINNED_SHA256:
        raise SystemExit(f"the vendored pattern set does not match its pinned digest: {digest} != {PINNED_SHA256}")
    escaped = pattern_text.replace("\\", "\\\\").replace("\"", "\\\"")
    lines = escaped.split("\n")
    literals = []
    current = []
    width = 0
    for line in lines:
        escaped_line = (line.replace("\\", "\\\\").replace("\"", "\\\"")) + "\\n"
        if width + len(escaped_line) > MAX_LINE_WIDTH and current:
            literals.append("".join(current))
            current = []
            width = 0
        current.append(escaped_line)
        width += len(escaped_line)
    if current:
        literals.append("".join(current))
    body = "\n".join(f'        "{literal}" +' for literal in literals)
    body = body[:-2]  # drop the trailing ' +'
    header = """// @generated by scripts/unicode/generate_hyphenation_source.py -- do not edit.

package org.graphiks.kalligraphie.unicode

/**
 * The vendored American-English hyphenation pattern set, embedded as a Kotlin constant.
 *
 * The pattern text is the byte-for-byte copy of the JVM module's
 * `hyph-en-us.pat.txt` resource, SHA-256
 * `%s`,
 * and this source is what `scripts/unicode/generate_hyphenation_source.py` emits from it.
 * The digest is verified at generation time, which is the equivalent of the JVM provider's
 * runtime verification: a changed or swapped pattern set cannot reach this source without
 * the generator refusing to emit it.
 */
internal object EmbeddedHyphenationPatterns {
    /** The pinned pattern set, one pattern per line, exactly as the JVM resource carries it. */
    internal const val englishPatterns: String =
""" % digest
    return header + body + "\n}\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write the source into the tree")
    parser.add_argument("--check", action="store_true", help="verify the committed source matches the pinned patterns")
    parser.add_argument("--root", default=".", help="repository root the paths resolve against")
    args = parser.parse_args()

    root = pathlib.Path(args.root)
    pattern_text = (root / PATTERN_RESOURCE).read_text(encoding="ascii")
    rendered = render(pattern_text)
    target = root / TARGET
    if args.write:
        target.write_text(rendered)
        print(f"wrote {target}")
    elif args.check:
        if not target.exists():
            raise SystemExit(f"{target} is missing; run with --write")
        if target.read_text() != rendered:
            raise SystemExit(f"{target} does not match the pinned pattern set")
        print("ok: the committed hyphenation source matches the pinned pattern set")


if __name__ == "__main__":
    main()
